export const INITIAL_BRANCHES = [
  "Azimpur Udvash",
  "Azimpur Udvash-Unmesh",
  "Badda Udvash",
  "Badda Udvash-Unmesh",
  "Bagerhat Udvash",
  "Bagerhat Udvash-Unmesh",
  "Bakshibazar Udvash",
  "Bakshibazar Udvash-Unmesh",
  "Banasree Udvash",
  "Banasree Udvash-Unmesh",
  "Bandarban Udvash",
  "Bandarban Udvash-Unmesh",
  "Barguna Udvash",
  "Barguna Udvash-Unmesh",
  "Barishal Udvash",
  "Barishal Udvash-Unmesh",
  "Basabo Udvash",
  "Basabo Udvash-Unmesh",
  "Belkuchi Udvash",
  "Belkuchi Udvash-Unmesh",
  "Bhairab Udvash",
  "Bhairab Udvash-Unmesh",
  "Bhaluka Udvash",
  "Bhaluka Udvash-Unmesh",
  "Bhola Udvash",
  "Bhola Udvash-Unmesh",
  "Birganj Udvash",
  "Birganj Udvash-Unmesh",
  "Bogura College Road Udvash",
  "Bogura College Road Udvash-Unmesh",
  "Bogura Sherpur Udvash",
  "Bogura Sherpur Udvash-Unmesh",
  "Bogura Udvash",
  "Bogura Udvash-Unmesh",
  "Bosila Udvash",
  "Bosila Udvash-Unmesh",
  "Brahmanbaria Udvash",
  "Brahmanbaria Udvash-Unmesh",
  "Cantonment Udvash",
  "Cantonment Udvash-Unmesh",
  "Chakaria Udvash",
  "Chakaria Udvash-Unmesh",
  "Chandpur Udvash",
  "Chandpur Udvash-Unmesh",
  "Chapainawabganj Udvash",
  "Chapainawabganj Udvash-Unmesh",
  "Charfasson Udvash",
  "Charfasson Udvash-Unmesh",
  "Chawkbazar Udvash (CTG)",
  "Chawkbazar Udvash-Unmesh",
  "Chuadanga Udvash",
  "Chuadanga Udvash-Unmesh",
  "Corporate Udvash",
  "Corporate Udvash-Unmesh",
  "Cox's Bazar Udvash",
  "Cox's Bazar Udvash-Unmesh",
  "Cumilla Tomsom Bridge Udvash",
  "Cumilla Tomsom Bridge Udvash-Unmesh",
  "Cumilla Udvash",
  "Cumilla Udvash-Unmesh",
  "Dhaka",
  "Dinajpur Udvash",
  "Dinajpur Udvash-Unmesh",
  "Donia Udvash",
  "Donia Udvash-Unmesh",
  "Examiner Branch",
  "Faridpur Udvash",
  "Faridpur Udvash-Unmesh",
  "Farmgate (GR) Udvash",
  "Farmgate (MT) Udvash",
  "Farmgate Udvash-Unmesh",
  "Feni Udvash",
  "Feni Udvash-Unmesh",
  "Gafargaon Udvash",
  "Gafargaon Udvash-Unmesh",
  "Gaibandha Udvash",
  "Gaibandha Udvash-Unmesh",
  "Gazipur Udvash",
  "Gazipur Udvash-Unmesh",
  "Ghatail Udvash",
  "Ghatail Udvash-Unmesh",
  "Gobindaganj Udvash",
  "Gobindaganj Udvash-Unmesh",
  "Gopalganj Udvash",
  "Gopalganj Udvash-Unmesh",
  "Habiganj Udvash",
  "Habiganj Udvash-Unmesh",
  "Halishahar Udvash (CTG)",
  "Halishahar Udvash-Unmesh",
  "Haziganj Udvash",
  "Haziganj Udvash-Unmesh",
  "Ishwardi Udvash",
  "Ishwardi Udvash-Unmesh",
  "Jamalpur Udvash",
  "Jamalpur Udvash-Unmesh",
  "Jashore Udvash",
  "Jashore Udvash-Unmesh",
  "Jatrabari Udvash",
  "Jatrabari Udvash-Unmesh",
  "Jhalakathi Udvash",
  "Jhalakathi Udvash-Unmesh",
  "Jhenaidah Udvash",
  "Jhenaidah Udvash-Unmesh",
  "Jigatola Udvash",
  "Jigatola Udvash-Unmesh",
  "Joypurhat Udvash",
  "Joypurhat Udvash-Unmesh",
  "Keraniganj Udvash",
  "Keraniganj Udvash-Unmesh",
  "Khagrachari Udvash",
  "Khagrachari Udvash-Unmesh",
  "Khilgaon Udvash",
  "Khilgaon Udvash-Unmesh",
  "Khulna Boyra Bazar Udvash",
  "Khulna Boyra Bazar Udvash-Unmesh",
  "Khulna Shantidham Mor Udvash",
  "Khulna Shantidham Mor Udvash-Unmesh",
  "Kishoreganj Udvash",
  "Kishoreganj Udvash-Unmesh",
  "Konapara Udvash",
  "Konapara Udvash-Unmesh",
  "Kurigram Udvash",
  "Kurigram Udvash-Unmesh",
  "Kushtia Udvash",
  "Kushtia Udvash-Unmesh",
  "Laksam Udvash",
  "Laksam Udvash-Unmesh",
  "Lakshmipur Udvash",
  "Lakshmipur Udvash-Unmesh",
  "Lalbagh Udvash",
  "Lalbagh Udvash-Unmesh",
  "Lalmonirhat Udvash",
  "Lalmonirhat Udvash-Unmesh",
  "Laxmibazar Udvash",
  "Laxmibazar Udvash-Unmesh",
  "Madaripur Udvash",
  "Madaripur Udvash-Unmesh",
  "Madhupur Udvash",
  "Madhupur Udvash-Unmesh",
  "Magura Udvash",
  "Magura Udvash-Unmesh",
  "Malibagh Udvash",
  "Malibagh Udvash-Unmesh",
  "Manikganj Udvash",
  "Manikganj Udvash-Unmesh",
  "Meherpur Udvash",
  "Meherpur Udvash-Unmesh",
  "Mirpur 1 Udvash",
  "Mirpur 1 Udvash-Unmesh",
  "Mirpur 2 Udvash",
  "Mirpur 2 Udvash-Unmesh",
  "Mohammadpur Udvash",
  "Mohammadpur Udvash-Unmesh",
  "Monohordi Udvash",
  "Monohordi Udvash-Unmesh",
  "Motijheel Udvash",
  "Motijheel Udvash-Unmesh",
  "Moulvibazar Udvash",
  "Moulvibazar Udvash-Unmesh",
  "Muktagacha Udvash",
  "Muktagacha Udvash-Unmesh",
  "Munshiganj Udvash",
  "Munshiganj Udvash-Unmesh",
  "Mymensingh (KB) Udvash",
  "Mymensingh (KB) Udvash-Unmesh",
  "Mymensingh Udvash",
  "Mymensingh Udvash-Unmesh",
  "Nageshwari Udvash",
  "Nageshwari Udvash-Unmesh",
  "Naogaon Udvash",
  "Naogaon Udvash-Unmesh",
  "Narail Udvash",
  "Narail Udvash-Unmesh",
  "Narayanganj Udvash",
  "Narayanganj Udvash-Unmesh",
  "Narsingdi Udvash",
  "Narsingdi Udvash-Unmesh",
  "Natore Udvash",
  "Natore Udvash-Unmesh",
  "Netrokona Udvash",
  "Netrokona Udvash-Unmesh",
  "Nilphamari Udvash",
  "Nilphamari Udvash-Unmesh",
  "Noakhali Udvash",
  "Noakhali Udvash-Unmesh",
  "Old Dhaka Udvash",
  "Online Udvash",
  "Oxygen Udvash (CTG)",
  "Oxygen Udvash-Unmesh",
  "Pabna Udvash",
  "Pabna Udvash-Unmesh",
  "Pallabi Udvash",
  "Pallabi Udvash-Unmesh",
  "Panchagarh Udvash",
  "Panchagarh Udvash-Unmesh",
  "Patenga Udvash",
  "Patenga Udvash-Unmesh",
  "Patiya Udvash",
  "Patiya Udvash-Unmesh",
  "Patuakhali Udvash",
  "Patuakhali Udvash-Unmesh",
  "Pirganj Rangpur Udvash",
  "Pirganj Rangpur Udvash-Unmesh",
  "Pirganj Thakurgaon Udvash",
  "Pirganj Thakurgaon Udvash-Unmesh",
  "Pirojpur Udvash",
  "Pirojpur Udvash-Unmesh",
  "Rajbari Udvash",
  "Rajbari Udvash-Unmesh",
  "Rajshahi Kadirganj Udvash",
  "Rajshahi Kadirganj Udvash-Unmesh",
  "Rajshahi Vodra Mor Udvash",
  "Rajshahi Vodra Mor Udvash-Unmesh",
  "Rangamati Udvash",
  "Rangamati Udvash-Unmesh",
  "Rangpur Khamar Mor Udvash",
  "Rangpur Khamar Mor Udvash-Unmesh",
  "Rangpur Medical Mor Udvash",
  "Rangpur Medical Mor Udvash-Unmesh",
  "Rokomari Distribution",
  "Rupnagar Udvash",
  "Rupnagar Udvash-Unmesh",
  "Saidpur Udvash",
  "Saidpur Udvash-Unmesh",
  "Sakhipur Udvash",
  "Sakhipur Udvash-Unmesh",
  "Satkhira Udvash",
  "Satkhira Udvash-Unmesh",
  "Savar Palli Bidyut Udvash",
  "Savar Palli Bidyut Udvash-Unmesh",
  "Savar Udvash",
  "Savar Udvash-Unmesh",
  "Science Lab Udvash",
  "Science Lab Udvash-Unmesh",
  "Shantinagar Udvash",
  "Shantinagar Udvash-Unmesh",
  "Shariatpur Udvash",
  "Shariatpur Udvash-Unmesh",
  "Sherpur Udvash",
  "Sherpur Udvash-Unmesh",
  "Sirajganj Udvash",
  "Sirajganj Udvash-Unmesh",
  "Sunamganj Udvash",
  "Sunamganj Udvash-Unmesh",
  "Sylhet Chowhatta Udvash",
  "Sylhet Chowhatta Udvash-Unmesh",
  "Sylhet Tilagor Udvash",
  "Sylhet Tilagor Udvash-Unmesh",
  "Tangail Udvash",
  "Tangail Udvash-Unmesh",
  "Thakurgaon Udvash",
  "Thakurgaon Udvash-Unmesh",
  "Tongi Udvash",
  "Tongi Udvash-Unmesh",
  "Ullapara Udvash",
  "Ullapara Udvash-Unmesh",
  "Uttara Azampur Udvash",
  "Uttara Azampur Udvash-Unmesh",
  "Uttara Diabari Udvash",
  "Uttara Diabari Udvash-Unmesh",
  "Uttara House Building Udvash",
  "Uttara House Building Udvash-Unmesh"
];
